### ISSUE TITLE
Dollies could potentially crash a server

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FluffyMachines#103]
## Description (Required)

Fluffy, currently you can use a dolly to pick up a chest. From there, you can place it into a backpack or shulker box, which can then be placed into a chest, and repeated over and over. If this goes deep enough there's the potential of causing server issues.

## Steps to reproduce the Issue (Required)

see above

## Expected behavior (Required)

Dollies, like shulkers and backpacks should not be able to be placed into backpacks or shulkers. Additionally they should not be able to be put back into chests.

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.17.1
 - CS-CoreLib Version:
 - Slimefun Version: 984
 - FluffyMachines Version: 94

**Comment by NCBPFluffyBear** [comment]
Have you tested this out? Because in practice this should never happen. Dollies exactly the same as backpacks, they are single items. Their contents are not stored in the metadata, like with shulkers, but rather in a file (see `\data-storage\Slimefun\Players`). If you were to go into the file, you would just see that the dolly contains a chest, which contains a dolly, etc. The only concern I had when making the dolly was that there was a theoretical infinite storage possibility, but I figured that it was so much of a hassle that it really didn't matter.

**Comment by Boomer-1** [comment]
we've got people already doing it on royale

**Comment by NCBPFluffyBear** [comment]
If that was the issue, disabling them shouldn't change anything; the data is still there and loaded whether dollies are enabled or not. Ill get in contact with lucky to try to solve the issue.

**Comment by NCBPFluffyBear** [comment]
https://user-images.githubusercontent.com/31554056/146815982-7c9ec944-86dc-4300-b279-999a3fd8a924.mp4

Was it any deeper than this? Had no issues from this so far but I can go deeper if necessary.

And to reinforce my earlier point a bit, here are the dolly contents:

![image](https://user-images.githubusercontent.com/31554056/146816113-35f49c51-7752-4916-ad05-8e5b77c2e0fc.png)
![image](https://user-images.githubusercontent.com/31554056/146816151-ea3d5b41-675c-491c-9eee-2b6c8a6b33b0.png)

The first ss shows one of the many dollies with the ACB cards, and the last shows the final dolly with all the shulkers of dollies with cards in it.

The search for CHEST shows that there are no chests here, so there shouldn't be any nesting.

**Comment by NCBPFluffyBear** [comment]
Closing due to inconclusive evidence that dollies cause crashing.
